---
abstract: 'add pod section from a Text::Template template'
author:
  - 'Jesse Luehrs <doy at tozt dot net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version (undef), CPAN::Meta::Converter version 2.101610'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-Section-Template
requires:
  Pod::Weaver: 0
  Text::Template: 0
resources:
  repository: git://github.com/doy/pod-weaver-section-template.git
version: 0.01
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@DOY/@Basic/GatherDir'
      version: ~
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@DOY/@Basic/PruneCruft'
      version: ~
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@DOY/@Basic/ManifestSkip'
      version: ~
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@DOY/@Basic/MetaYAML'
      version: ~
    -
      class: Dist::Zilla::Plugin::License
      name: '@DOY/@Basic/License'
      version: ~
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@DOY/@Basic/Readme'
      version: ~
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@DOY/@Basic/ExtraTests'
      version: ~
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@DOY/@Basic/ExecDir'
      version: ~
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@DOY/@Basic/ShareDir'
      version: ~
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@DOY/@Basic/MakeMaker'
      version: ~
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@DOY/@Basic/Manifest'
      version: ~
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@DOY/@Basic/TestRelease'
      version: ~
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@DOY/@Basic/ConfirmRelease'
      version: ~
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@DOY/@Basic/UploadToCPAN'
      version: ~
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@DOY/MetaConfig'
      version: ~
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@DOY/MetaJSON'
      version: ~
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@DOY/NextRelease'
      version: ~
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@DOY/PkgVersion'
      version: ~
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@DOY/PodCoverageTests'
      version: ~
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@DOY/PodSyntaxTests'
      version: ~
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@DOY/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@DOY/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@DOY/CompileTests'
      version: 1.101600
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@DOY/Repository'
      version: 0.13
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@DOY/Git::Check'
      version: ~
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@DOY/Git::Tag'
      version: ~
    -
      class: Dist::Zilla::Plugin::Git::VersionFromTag
      name: '@DOY/Git::VersionFromTag'
      version: ~
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@DOY/PodWeaver'
      version: 3.101530
    -
      class: Dist::Zilla::Plugin::Prereq
      config:
        Dist::Zilla::Plugin::Prereq:
          phase: runtime
          type: requires
      name: Prereq
      version: ~
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: ~
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: ~
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: ~
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: ~
  zilla:
    class: Dist::Zilla
    config:
      is_trial: 0
    version: ~
